### ISSUE TITLE
Feature Request : Custom Artifacts Upload for Scikit/XGB Inference 

### ISSUE THREAD

**Issue by ucalyptus** [shaz13/katana#28]
- [ ] Lets me upload joblib/pkl file (FEATURE REQUEST) for scikit/xgb trained models.
- [x] I am allowed to edit a payload json.
- [x] Hit on Execute to perform inference on my joblib model with the pred_input.json as input and printout status(200 Success) and confidence/other metrics.

The above can be done using GCS where I have to create a bucket and use their AI Platform for prediction phase. However that is not beginner-friendly and requires a lot of preliminary GCP setups and API enabling overheads.

Please look into this @shaz13 @shaz13-socgen @AdityaSoni19031997

**Comment by shaz13** [comment]
Hi @ucalyptus, 
-  Lets me upload joblib/pkl file (FEATURE REQUEST) for scikit/xgb trained models.

Sure, we can look forward to add an example to consume a model and process inference. We will add it in our upcoming feature list
 
-  I am allowed to edit a payload JSON
- Hit on Execute to perform inference on my joblib model with the pred_input.json as input and printout status(200 Success) and confidence/other metrics.

Our swagger integration should already allow you to edit your payload.json. 
> Please refer here -https://katana-demo.herokuapp.com/
    https://katana-demo.herokuapp.com/inference/UCIDiabetes

You can always send some additional information and set expectations from the payload. 
Please let me know if you are talking about something else.

**Comment by ucalyptus** [comment]
Yes I only meant about the model uploading part. Rest is all fine. Yes, I have seen your examples.

**Comment by AdityaSoni19031997** [comment]
Also the user has to specify, which model it's otherwise we cannot load it correctly!

**Comment by shaz13-socgen** [comment]
We can only stick to scikit learning models first and incrementally support XGB models. 
But I am really thinking into actual use for this feature in real word.
