### ISSUE TITLE
Adding Authentication to Swagger API calls

### ISSUE THREAD

**Issue by shaz13** [shaz13/katana#33]

**Comment by AdityaSoni19031997** [comment]
Does this mean that we will also have to have a way for user sign-up as well? And the credentials being cached to a dB or something?

**Comment by tejasa97** [comment]
@shaz13 is there a user sign-in implemented?

**Comment by shaz13** [comment]
No, not yet. Right now we have bare minimum boilerplate code. And, we don't want to code something very specific that won't be generalizable in real world.

**Comment by shaz13** [comment]
However, an example on authentication token and authorized API call is what we seek from this issue.
Ref - https://swagger.io/docs/specification/authentication/

**Comment by tejasa97** [comment]
You can implement JWT auth. But like I said, you will definitely need a auth route for this. 
Eg : Who all can obtain a JWT token? What kind of criteria should be considered before providing a JWT token to a user for use? And, once granted, how long should it be valid?
