### ISSUE TITLE
[Feature Request] : Use gRPC instead of REST/RestX

### ISSUE THREAD

**Issue by ucalyptus** [shaz13/katana#39]
Protocol Buffers are better than REST JSON.
[Have a look at this example I made today](https://github.com/ucalyptus/scikit-on-gRPC)

**Comment by shaz13-socgen** [comment]
Currently the objective of the project is building a flask-restful API template. 
We are however working on RPC stuff and looking into testing RabbitMQ and other practices that is intended most likely to be a separate template and out of scope for this project. 

Closing for now
