### ISSUE TITLE
Logging at gunicorn.access is not working. All goes into gunicorn.error

### ISSUE THREAD

**Issue by shaz13-socgen** [shaz13/katana#40]

**Comment by shaz13-socgen** [comment]
@AdityaSoni19031997 Please take a look and see if you can reproduce.

**Comment by AdityaSoni19031997** [comment]
In my experiments, this shouldn't happen if the app is run using gunicorn?

**Comment by shaz13-socgen** [comment]
@AdityaSoni19031997 same with gunicorn. 
Tested on macOS Catalina and Windows 10

**Comment by AdityaSoni19031997** [comment]
Hopefully Resolved via https://github.com/shaz13/katana/pull/41
