### ISSUE TITLE
Python version

### ISSUE THREAD

**Issue by tejasa97** [shaz13/katana#42]
Specify the python runtime version (3.6, 3.7, 3.8?), and update the `runtime.txt` for Heroku, and the Dockerfile for local/cloud deployment.

**Comment by shaz13** [comment]
Hey @tejasa97, 
Just checking, are you working on it.

**Comment by tejasa97** [comment]
@shaz13 Sorry, haven't been very active recently! Been busy on the workfront. Will try and make progress this week.
